#AMREX_HOME defines the directory in which we will find the BoxLib directory
AMREX_HOME ?= ~/Desktop/Amrax_tutorial/amrex
AMREX_HYDRO_HOME ?= ~/Desktop/Amrax_tutorial/AMReX-Hydro

#TOP defines the directory in which we will find Source, Exec, etc.
TOP = ~/Desktop/Amrax_tutorial/IAMR

#
# Variables for the user to set ...
#

PRECISION   = DOUBLE

DIM         = 2
COMP        = gnu

DEBUG       = FALSE`¬`
USE_MPI     = FALSE
USE_OMP     = FALSE
PROFILE     = FALSE

USE_CUDA = FALSE

USE_SENSEI_INSITU = FALSE

EBASE = amr

Blocs   := .

include $(TOP)/Exec/Make.IAMR
